import json
import requests
from openai import OpenAI
from tabulate import tabulate

# =====================================================================
# GLOBAL CONFIGURATION (Modify only if you know what you're doing)
# =====================================================================
API_KEY = "your_api_key_here"  # Replace with your actual API key from Groq or OpenAI
BASE_URL = "https://api.groq.com/openai/v1"  
DEFAULT_MODELS = ["openai/gpt-oss-120b"] #a list in case you want to use multiple models for comparison


class SwarmReporter:
    def __init__(self, api_key=API_KEY, base_url=BASE_URL, models=None):
        self.api_key = api_key
        self.base_url = base_url
        self.client = OpenAI(api_key=self.api_key, base_url=self.base_url)
        self.models = models if models is not None else list(DEFAULT_MODELS)

    def generate_report(self, transcript_text, debug=False):
        """
        Generate a structured report from the given transcript text using multiple models.
        Returns a dictionary with model names as keys and their respective reports as values.
        """
        prompt = f"""You are an AI agent communication analyst. Review the following conversation 
transcript or task log between agents and humans. 

--- TRANSCRIPT START ---
{transcript_text}
--- TRANSCRIPT END ---

Instructions:
Extract the most important topics discussed.
Generate a brief executive summary (maximum 3 sentences).
List the decisions, agreements, or final outcomes reached.

Respond ONLY in valid JSON format using the following structure (without extra markdown code blocks):
{
"summary": "Summary here...",
"key_topics": ["Topic 1", "Topic 2", "Topic 3"],
"agreements_or_outcomes": ["Outcome 1", "Outcome 2"]
}
"""
        reports = {}

        for model_name in self.models: 
            print(f"Generating report with model: {model_name}...")
            try:
                response = self.client.chat.completions.create(
                    messages=[{"role": "user", "content": prompt}],
                    model=model_name,
                    temperature=0.2,  # low temperature for more deterministic output
                )
                
                content = response.choices[0].message.content.strip()

                # cleaning in case the model has marks ```json ... ```
                if content.startswith("```"):
                    content = content.split("\n", 1)[1].rsplit("\n", 1)[0]
                    if content.startswith("json"):
                        content = content[4:].strip()

                parsed_json = json.loads(content)
                reports[model_name] = parsed_json

            except Exception as e:
                print(f"Error using the model {model_name}: {e}")
                reports[model_name] = None

        return reports

    def print_formatted_reports(self, reports):
        """Print the reports in a structured and readable format."""
        for model_name, data in reports.items():
            print("\n" + "=" * 60)
            print(f"Report generated by: {model_name}")
            print("=" * 60)

            if not data:
                print("No report could be generated.")
                continue

            print(f"\nEXECUTIVE SUMMARY:\n{data.get('summary', 'N/A')}\n")

            print(" KEY TOPICS:")
            for tema in data.get("key_topics", []):
                print(f"  • {tema}")

            print("\n ACUERDOS / RESULTADOS:")
            for acuerdo in data.get("agreements_or_outcomes", []):
                print(f"  • {acuerdo}")
            print("\n")